language: node_js
node_js:
  - 9

cache:
  directories:
    - 'node_modules'

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  email: chenxiaowue1994@outlook.com
  name: travis build